spring:
  application:
    name: demo
  profiles:
    active: 'loc'
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: false
    open-in-view: false
  output:
    ansi:
      enabled: detect
